file_format: "1"
id: "Sonny's"
name: "Sonny's"
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - charybdis_left
  - charybdis_right
